version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/frontend"
      - "/backend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directories:
      - "/frontend"
      - "/backend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "terraform"
    directory: "/infra/terraform"
    schedule:
      interval: "monthly"
