-- Fresh-project target schema for Workout-Journal.
-- This migration is intentionally forward-only and is not a copy of an
-- unverified live schema. Apply it only to a new Supabase project.

create table public.users (
  uuid uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text
);

create table public.notes (
  date text not null,
  note text,
  exercises text,
  userid uuid not null references public.users(uuid) on delete cascade,
  tags text[],
  primary key (date, userid)
);

create index notes_userid_date_idx on public.notes (userid, date);
create index notes_tags_gin_idx on public.notes using gin (tags);

create table public.user_tags (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.users(uuid) on delete cascade,
  tag text not null,
  unique (user_id, tag)
);

-- The current application accesses database data only through its backend.
-- Service-role access is configured outside this migration; no browser-facing
-- anon/authenticated policies are created here.
alter table public.users enable row level security;
alter table public.notes enable row level security;
alter table public.user_tags enable row level security;

revoke all on table public.users from anon, authenticated, service_role;
revoke all on table public.notes from anon, authenticated, service_role;
revoke all on table public.user_tags from anon, authenticated, service_role;
revoke all on sequence public.user_tags_id_seq from anon, authenticated, service_role;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.users to service_role;
grant select, insert, update, delete on table public.notes to service_role;
grant select, insert, update, delete on table public.user_tags to service_role;
grant usage, select on sequence public.user_tags_id_seq to service_role;
